const { test, expect } = require('../../src/fixtures');
const {
  createUserResponseSchema,
  getUserResponseSchema,
  errorResponseSchema,
} = require('../../src/api/schemas/user.schemas');
const { generateUserPayload } = require('../../src/data/test-data-generator');
const {
  JSON_CONTENT_TYPE,
  VALID_AGE_BOUNDARIES,
  USER_TYPES,
  invalidCreateUserPayloads,
} = require('../../src/data/user-api-data');

/**
 * Task 3.2 — POST /user accepts username (string), age (integer within 1-100)
 * and user_type (boolean), and answers with user_id and username.
 */
test.describe('POST /user', { tag: '@api' }, () => {
  test('Creates a user and returns user_id and username', async ({ userApi }) => {
    const payload = generateUserPayload();

    const response = await userApi.createUser(payload);

    expect(response.status).toBe(201);
    expect(response.headers['content-type']).toMatch(JSON_CONTENT_TYPE);
    expect(response.body).toMatchSchema(createUserResponseSchema);
    expect(response.body.username).toBe(payload.username);
    expect(response.body.user_id, 'user_id must be generated by the API').toBeTruthy();
  });

  test('Assigns a distinct user_id to every created user', async ({ userApi }) => {
    const [first, second] = await Promise.all([
      userApi.createUser(generateUserPayload()),
      userApi.createUser(generateUserPayload()),
    ]);

    expect(first.status).toBe(201);
    expect(second.status).toBe(201);
    expect(first.body.user_id).not.toBe(second.body.user_id);
  });

  for (const { title, age } of VALID_AGE_BOUNDARIES) {
    test(`Accepts age at the ${title}`, async ({ userApi }) => {
      const payload = generateUserPayload({ age });

      const response = await userApi.createUser(payload);

      expect(response.status).toBe(201);
      expect(response.body).toMatchSchema(createUserResponseSchema);
    });
  }

  for (const { title, userType } of USER_TYPES) {
    test(`Creates a ${title}`, async ({ userApi }) => {
      const payload = generateUserPayload({ user_type: userType });

      const created = await userApi.createUser(payload);
      expect(created.status).toBe(201);
      expect(created.body).toMatchSchema(createUserResponseSchema);

      // The created user must be retrievable with the data it was created from.
      const fetched = await userApi.getUser(created.body.user_id);
      expect(fetched.status).toBe(200);
      expect(fetched.body).toMatchSchema(getUserResponseSchema);
      expect(fetched.body.username).toBe(payload.username);
      expect(fetched.body.age).toBe(payload.age);
    });
  }

  for (const { title, payload } of invalidCreateUserPayloads()) {
    test(`Rejects a payload with ${title}`, async ({ userApi }) => {
      const response = await userApi.createUser(payload);

      expect(response.status).toBe(400);
      expect(response.body).toMatchSchema(errorResponseSchema);
    });
  }

  test('Rejects an empty request body', async ({ userApi }) => {
    const response = await userApi.createUser(undefined);

    expect(response.status).toBe(400);
    expect(response.body).toMatchSchema(errorResponseSchema);
  });
});
